In [1]:
import yfinance as yf #importar el modulo yfinance

In [2]:
sura=yf.Ticker("PFGRUPSURA.CL")

"""El módulo Ticker, que le permite acceder a los datos de ticker de una manera más pitónica:"""

In [3]:
sura.info

{'address1': 'Carrera 43A #5A',
 'address2': 'Piso 13-15',
 'city': 'Medellín',
 'zip': '113',
 'country': 'Colombia',
 'phone': '57 18000 521 555',
 'website': 'https://www.gruposura.com',
 'industry': 'Insurance—Diversified',
 'industryDisp': 'Insurance—Diversified',
 'sector': 'Financial Services',
 'longBusinessSummary': 'Grupo de Inversiones Suramericana S.A. operates in the financial services, industry, and corporate venture sectors in Colombia and internationally. It offers general and life insurance, as well as reinsurance products; pension, saving, investment, and asset management services; investment funds; life annuities; severance pay and complementary services; health plans; occupational risks; and commercial, consumer, insurance, investment, offshore, private, and government banking, as well as treasury products. The company also produces cement, concrete, and aggregates; provides processed foods, such as cold cuts, crackers, chocolates, coffees, ice cream, pasta, and consumer foods; and offers power generation and distribution, real estate, road and airport concessions, and business support services. In addition, it provides a talent development platform; technology solutions for real estate investors, insurance industry, and health insurance company, as well as in the areas of road safety, and water and energy; a platform for engagement, marketing, sale, and administration of financial products; a health technology platform; individuals to optimize their wellness and lower healthcare costs; web and mobile platform based on artificial intelligence; and risk capital fund for early-stage and growing technology companies. Further, the company offers integrated information, technology, and knowledge solutions; and residential, functional conditioning, and rehabilitation services for the senior citizen. Additionally, it provides data processing and leasing computer equipment, consultancy and advisory, promotion, and marketing services; management consultancy services; medical, paramedical, dental, and diagnostic aid services; risk management, telecommunication, and outsourcing services; and vehicle inspection, repair, purchase, and selling services, as well as acts as securities brokers; and purchases and sells securities. The company was incorporated in 1997 and is headquartered in Medellin, Colombia.',
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Gonzalo Alberto  Perez Rojas',
   'age': 64,
   'title': 'Chief Exec. Officer',
   'yearBorn': 1958,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ricardo  Jaramillo Mejia',
   'title': 'Chief Bus. Devel. & Fin. Officer',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Juan Camilo  Parra Osorio',
   'title': 'Investment & Treasury Mang.',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Luis Fernando  Soto Salazar',
   'title': 'Chief Accountant',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Juan  Carlos Gómez',
   'title': 'Mang. of Investor Relations',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Juan Luis  Munera Gomez',
   'age': 50,
   'title': 'Chief Corp. Legal Affairs Officer & Company Sec.',
   'yearBorn': 1972,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Paula Cecilia Villegas Hincapie',
   'title': 'Communications & Corp. Identity Mang.',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Carlos Eduardo Gonzalez Tabares',
   'title': 'Managing Director of Investors & Capital Markets',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Ruth de Solorzano',
   'title': 'Pres of AFP Crecer El Salvador',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ignacio  Calle Cuartas',
   'title': 'Chief Exec. Officer of Sura Asset Management',
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 11250.0,
 'open': 0.0,
 'dayLow': 11250.0,
 'dayHigh': 11250.0,
 'regularMarketPreviousClose': 11250.0,
 'regularMarketOpen': 0.0,
 'regularMarketDayLow': 11250.0,
 'regularMarketDayHigh': 11250.0,
 'dividendRate': 1280.0,
 'dividendYield': 0.113800004,
 'exDividendDate': 1687824000,
 'payoutRatio': 0.219,
 'fiveYearAvgDividendYield': 3.06,
 'beta': 0.612397,
 'trailingPE': 2.7137074,
 'volume': 0,
 'regularMarketVolume': 0,
 'averageVolume': 52393,
 'averageVolume10days': 22648,
 'averageDailyVolume10Day': 22648,
 'bid': 0.0,
 'ask': 0.0,
 'marketCap': 19981236436992,
 'fiftyTwoWeekLow': 9600.0,
 'fiftyTwoWeekHigh': 23000.0,
 'priceToSalesTrailing12Months': 0.51906985,
 'fiftyDayAverage': 11230.2,
 'twoHundredDayAverage': 12595.05,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'COP',
 'enterpriseValue': 16616195620864,
 'profitMargins': 0.06442,
 'floatShares': 171664912,
 'sharesOutstanding': 112508000,
 'heldPercentInsiders': 0.08108,
 'heldPercentInstitutions': 0.61103,
 'bookValue': 57169.867,
 'priceToBook': 0.196782,
 'lastFiscalYearEnd': 1672444800,
 'nextFiscalYearEnd': 1703980800,
 'mostRecentQuarter': 1680220800,
 'earningsQuarterlyGrowth': 0.943,
 'netIncomeToCommon': 2459917877248,
 'trailingEps': 4145.62,
 'enterpriseToRevenue': 0.432,
 'enterpriseToEbitda': 3.378,
 '52WeekChange': -0.48060942,
 'SandP52WeekChange': 0.017738938,
 'lastDividendValue': 320.0,
 'lastDividendDate': 1703548800,
 'exchange': 'BVC',
 'quoteType': 'EQUITY',
 'symbol': 'PFGRUPSURA.CL',
 'underlyingSymbol': 'PFGRUPSURA.CL',
 'shortName': 'GPO DE INVERSIONES',
 'longName': 'Grupo de Inversiones Suramericana S.A.',
 'firstTradeDateEpochUtc': 1323181800,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': '83a4f2ca-121b-3e39-8b01-1fd0141b9e56',
 'messageBoardId': 'finmb_883286',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 11250.0,
 'recommendationKey': 'none',
 'totalCash': 3549015048192,
 'totalCashPerShare': 5947.107,
 'ebitda': 4918814965760,
 'totalDebt': 11333105876992,
 'quickRatio': 2.038,
 'currentRatio': 2.524,
 'totalRevenue': 38494311284736,
 'debtToEquity': 31.276,
 'revenuePerShare': 66999.89,
 'returnOnAssets': 0.03076,
 'returnOnEquity': 0.08465,
 'grossProfits': 9986000000000,
 'freeCashflow': 261911625728,
 'operatingCashflow': 10232986075136,
 'earningsGrowth': 0.865,
 'revenueGrowth': 0.407,
 'grossMargins': 0.31822002,
 'ebitdaMargins': 0.12778,
 'operatingMargins': 0.11165,
 'financialCurrency': 'COP',
 'trailingPegRatio': None}

In [5]:
hist = sura.history(period="1mo") """devuelve un objeto pandas con el historico de la accion"""
print(hist)

                              Open     High      Low    Close  Volume  \
Date
2023-05-02 00:00:00-04:00  11440.0  11510.0  11230.0  11250.0   37410
2023-05-03 00:00:00-04:00  11380.0  11480.0  11230.0  11250.0   33304
2023-05-04 00:00:00-04:00  11200.0  11200.0  11000.0  11000.0    9640
2023-05-05 00:00:00-04:00  11350.0  11420.0  11300.0  11300.0   22458
2023-05-08 00:00:00-04:00  11360.0  11500.0  11360.0  11420.0   33582
2023-05-09 00:00:00-04:00  11470.0  11470.0  11410.0  11410.0    3948
2023-05-10 00:00:00-04:00  11500.0  11500.0  11400.0  11400.0   35907
2023-05-11 00:00:00-04:00  11490.0  11620.0  11490.0  11620.0   61963
2023-05-12 00:00:00-04:00  11630.0  11990.0  11600.0  11600.0   44197
2023-05-15 00:00:00-04:00  11600.0  11600.0  11470.0  11490.0   23285
2023-05-16 00:00:00-04:00  11500.0  11500.0  11360.0  11360.0   27343
2023-05-17 00:00:00-04:00  11360.0  11360.0  11310.0  11340.0   25269
2023-05-18 00:00:00-04:00  11340.0  11340.0  11110.0  11130.0   23100
2023-05-19 00:00:00-04:00  11140.0  11450.0  11140.0  11450.0   38499
2023-05-23 00:00:00-04:00  11450.0  11500.0  11450.0  11460.0   11115
2023-05-24 00:00:00-04:00  11460.0  11500.0  11250.0  11250.0   33681
2023-05-25 00:00:00-04:00  11250.0  11250.0  11250.0  11250.0       0
2023-05-26 00:00:00-04:00  11250.0  11250.0  11250.0  11250.0       0

                           Dividends  Stock Splits
Date
2023-05-02 00:00:00-04:00        0.0           0.0
2023-05-03 00:00:00-04:00        0.0           0.0
2023-05-04 00:00:00-04:00        0.0           0.0
2023-05-05 00:00:00-04:00        0.0           0.0
2023-05-08 00:00:00-04:00        0.0           0.0
2023-05-09 00:00:00-04:00        0.0           0.0
2023-05-10 00:00:00-04:00        0.0           0.0
2023-05-11 00:00:00-04:00        0.0           0.0
2023-05-12 00:00:00-04:00        0.0           0.0
2023-05-15 00:00:00-04:00        0.0           0.0
2023-05-16 00:00:00-04:00        0.0           0.0
2023-05-17 00:00:00-04:00        0.0           0.0
2023-05-18 00:00:00-04:00        0.0           0.0
2023-05-19 00:00:00-04:00        0.0           0.0
2023-05-23 00:00:00-04:00        0.0           0.0
2023-05-24 00:00:00-04:00        0.0           0.0
2023-05-25 00:00:00-04:00        0.0           0.0
2023-05-26 00:00:00-04:00        0.0           0.0

In [6]:
print(type(hist))

<class 'pandas.core.frame.DataFrame'>

In [7]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-05-02 00:00:00-04:00,11440.0,11510.0,11230.0,11250.0,37410,0.0,0.0
2023-05-03 00:00:00-04:00,11380.0,11480.0,11230.0,11250.0,33304,0.0,0.0
2023-05-04 00:00:00-04:00,11200.0,11200.0,11000.0,11000.0,9640,0.0,0.0
2023-05-05 00:00:00-04:00,11350.0,11420.0,11300.0,11300.0,22458,0.0,0.0
2023-05-08 00:00:00-04:00,11360.0,11500.0,11360.0,11420.0,33582,0.0,0.0
2023-05-09 00:00:00-04:00,11470.0,11470.0,11410.0,11410.0,3948,0.0,0.0
2023-05-10 00:00:00-04:00,11500.0,11500.0,11400.0,11400.0,35907,0.0,0.0
2023-05-11 00:00:00-04:00,11490.0,11620.0,11490.0,11620.0,61963,0.0,0.0
2023-05-12 00:00:00-04:00,11630.0,11990.0,11600.0,11600.0,44197,0.0,0.0
2023-05-15 00:00:00-04:00,11600.0,11600.0,11470.0,11490.0,23285,0.0,0.0
2023-05-16 00:00:00-04:00,11500.0,11500.0,11360.0,11360.0,27343,0.0,0.0
2023-05-17 00:00:00-04:00,11360.0,11360.0,11310.0,11340.0,25269,0.0,0.0
2023-05-18 00:00:00-04:00,11340.0,11340.0,11110.0,11130.0,23100,0.0,0.0
2023-05-19 00:00:00-04:00,11140.0,11450.0,11140.0,11450.0,38499,0.0,0.0
2023-05-23 00:00:00-04:00,11450.0,11500.0,11450.0,11460.0,11115,0.0,0.0
2023-05-24 00:00:00-04:00,11460.0,11500.0,11250.0,11250.0,33681,0.0,0.0
2023-05-25 00:00:00-04:00,11250.0,11250.0,11250.0,11250.0,0,0.0,0.0
2023-05-26 00:00:00-04:00,11250.0,11250.0,11250.0,11250.0,0,0.0,0.0

In [8]:
sura.history_metadata # mostrar metainformación sobre el historial (requiere que se llame primero a history())

{'currency': 'COP',
 'symbol': 'PFGRUPSURA.CL',
 'exchangeName': 'BVC',
 'instrumentType': 'EQUITY',
 'firstTradeDate': Timestamp('2011-12-06 09:30:00-0500', tz='America/New_York'),
 'regularMarketTime': Timestamp('2023-05-24 15:32:41-0400', tz='America/New_York'),
 'gmtoffset': -14400,
 'timezone': 'EDT',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 11250.0,
 'chartPreviousClose': 11600.0,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'start': Timestamp('2023-05-29 09:30:00-0400', tz='America/New_York'),
   'end': Timestamp('2023-05-29 09:30:00-0400', tz='America/New_York')},
  'regular': {'start': Timestamp('2023-05-29 09:30:00-0400', tz='America/New_York'),
   'end': Timestamp('2023-05-29 16:00:00-0400', tz='America/New_York')},
  'post': {'start': Timestamp('2023-05-29 16:00:00-0400', tz='America/New_York'),
   'end': Timestamp('2023-05-29 16:00:00-0400', tz='America/New_York')}},
 'dataGranularity': '1d',
 'range': '1mo',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [11]:
# show actions (dividends, splits, capital gains)
print(sura.actions)
print(sura.dividends)
sura.splits
sura.capital_gains  # only for mutual funds & etfs

Empty DataFrame
Columns: [Dividends, Stock Splits]
Index: []
Series([], Name: Dividends, dtype: float64)

[]

In [17]:
print(sura.recommendations)
print(sura.recommendations_summary)

None
None

In [18]:
## multiples tickers

tickers = yf.Tickers('msft aapl PFGRUPSURA.CL')

In [19]:
# acceder a cada informacion de las acciones traidas

tickers.tickers['MSFT'].info
tickers.tickers['AAPL'].history(period="1mo")
tickers.tickers['PFGRUPSURA.CL'].actions

                           Dividends  Stock Splits
Date
2012-06-26 00:00:00-04:00     243.75           0.0
2012-09-25 00:00:00-04:00     243.75           0.0
2012-12-24 00:00:00-05:00     243.75           0.0
2012-12-26 00:00:00-05:00     243.75           0.0
2013-03-21 00:00:00-04:00     243.75           0.0
2013-03-22 00:00:00-04:00     243.75           0.0
2013-06-25 00:00:00-04:00     243.75           0.0
2013-09-25 00:00:00-04:00     243.75           0.0
2013-12-24 00:00:00-05:00     243.75           0.0
2013-12-26 00:00:00-05:00     243.75           0.0
2014-03-26 00:00:00-04:00     243.75           0.0
2014-06-24 00:00:00-04:00     243.75           0.0
2014-09-25 00:00:00-04:00     243.75           0.0
2014-12-24 00:00:00-05:00     195.00           0.0
2015-03-30 00:00:00-04:00     105.50           0.0
2015-06-24 00:00:00-04:00     105.50           0.0
2015-09-25 00:00:00-04:00     105.50           0.0
2015-12-24 00:00:00-05:00     105.50           0.0
2016-04-04 00:00:00-04:00     114.00           0.0
2016-06-27 00:00:00-04:00     114.00           0.0
2016-07-05 00:00:00-04:00     114.00           0.0
2016-09-27 00:00:00-04:00     114.00           0.0
2016-10-04 00:00:00-04:00     114.00           0.0
2016-12-26 00:00:00-05:00     114.00           0.0
2016-12-27 00:00:00-05:00     114.00           0.0
2017-01-03 00:00:00-05:00     114.00           0.0
2017-04-17 00:00:00-04:00     488.00           0.0
2018-03-23 00:00:00-04:00     129.50           0.0
2018-04-16 00:00:00-04:00     518.00           0.0
2018-06-26 00:00:00-04:00     129.50           0.0
2018-09-25 00:00:00-04:00     129.50           0.0
2018-12-26 00:00:00-05:00     129.50           0.0
2019-04-08 00:00:00-04:00     137.50           0.0
2019-06-25 00:00:00-04:00     137.50           0.0
2019-09-25 00:00:00-04:00     137.50           0.0
2019-12-26 00:00:00-05:00     137.50           0.0
2020-04-14 00:00:00-04:00     145.75           0.0
2020-06-24 00:00:00-04:00      51.00           0.0
2020-09-25 00:00:00-04:00     145.75           0.0
2020-12-24 00:00:00-05:00     145.75           0.0
2020-12-28 00:00:00-05:00     145.75           0.0
2021-04-13 00:00:00-04:00     150.85           0.0
2021-06-25 00:00:00-04:00     150.85           0.0
2021-09-27 00:00:00-04:00     150.85           0.0
2021-12-27 00:00:00-05:00     150.85           0.0
2021-12-28 00:00:00-05:00     150.85           0.0
2022-03-28 00:00:00-04:00     196.00           0.0
2022-06-24 00:00:00-04:00     196.00           0.0
2022-09-27 00:00:00-04:00     196.00           0.0
2022-12-27 00:00:00-05:00     196.00           0.0
2023-04-04 00:00:00-04:00     320.00           0.0

In [22]:
print(type(tickers))

<class 'yfinance.tickers.Tickers'>

In [23]:
yf.download(tickers = "msft aapl PFGRUPSURA.CL",  # list of tickers
            period = "1y",         # time period
            interval = "1d",       # trading interval
            prepost = False,       # download pre/post market hours data?
            repair = True)         # repair obvious price errors e.g. 100x?

[                       0%                       ]PFGRUPSURA.CL: fixed 7/1035 value=0 errors in 1h price data
PFGRUPSURA.CL: fixed 7/49 value=0 errors in 1d price data
[*********************100%***********************]  3 of 3 completed

             Adj Close                                 Close              \
                  AAPL        MSFT PFGRUPSURA.CL        AAPL        MSFT
Date
2022-05-27  148.751770  270.624084           NaN  149.639999  273.239990
2022-05-30         NaN         NaN  20178.792969         NaN         NaN
2022-05-31  147.956528  269.267242  20775.029297  148.839996  271.869995
2022-06-01  147.827301  269.811951  20178.792969  148.710007  272.420013
2022-06-02  150.312454  271.951233  20914.771484  151.210007  274.579987
...                ...         ...           ...         ...         ...
2023-05-22  174.199997  321.179993           NaN  174.199997  321.179993
2023-05-23  171.559998  315.260010  11460.000000  171.559998  315.260010
2023-05-24  171.839996  313.850006  11250.000000  171.839996  313.850006
2023-05-25  172.990005  325.920013  11250.000000  172.990005  325.920013
2023-05-26  175.429993  332.890015  11250.000000  175.429993  332.890015

                                High                                   Low  \
           PFGRUPSURA.CL        AAPL        MSFT PFGRUPSURA.CL        AAPL
Date
2022-05-27           NaN  149.679993  273.339996           NaN  145.259995
2022-05-30       21660.0         NaN         NaN       21660.0         NaN
2022-05-31       22300.0  150.660004  274.769989       23000.0  146.839996
2022-06-01       21660.0  151.740005  277.690002       21660.0  147.679993
2022-06-02       22450.0  151.270004  274.649994       22800.0  146.860001
...                  ...         ...         ...           ...         ...
2023-05-22           NaN  174.710007  322.589996           NaN  173.449997
2023-05-23       11460.0  173.380005  322.720001       11500.0  171.279999
2023-05-24       11250.0  172.419998  316.500000       11500.0  170.520004
2023-05-25       11250.0  173.899994  326.899994       11250.0  171.690002
2023-05-26       11250.0  175.770004  333.399994       11250.0  173.110001

                                            Open                            \
                  MSFT PFGRUPSURA.CL        AAPL        MSFT PFGRUPSURA.CL
Date
2022-05-27  267.559998           NaN  145.389999  268.480011           NaN
2022-05-30         NaN       21660.0         NaN         NaN       21660.0
2022-05-31  268.929993       21950.0  149.070007  272.529999       22300.0
2022-06-01  270.040009       21660.0  149.899994  275.200012       21660.0
2022-06-02  261.600006       22380.0  147.830002  264.450012       22450.0
...                ...           ...         ...         ...           ...
2023-05-22  318.010010           NaN  173.979996  318.600006           NaN
2023-05-23  315.250000       11450.0  173.130005  320.029999       11450.0
2023-05-24  312.609985       11250.0  171.089996  314.730011       11460.0
2023-05-25  320.000000       11250.0  172.410004  323.239990       11250.0
2023-05-26  323.880005       11250.0  173.320007  324.019989       11250.0

                 Volume
                   AAPL        MSFT PFGRUPSURA.CL
Date
2022-05-27   90978500.0  26910800.0           NaN
2022-05-30          NaN         NaN           0.0
2022-05-31  103718400.0  37827700.0      171599.0
2022-06-01   74286600.0  25292200.0           0.0
2022-06-02   72348100.0  44008200.0      129090.0
...                 ...         ...           ...
2023-05-22   43570900.0  24115700.0           NaN
2023-05-23   50747300.0  30797200.0       11115.0
2023-05-24   45143500.0  23384900.0       33681.0
2023-05-25   56058300.0  43301700.0           0.0
2023-05-26   54794100.0  36600900.0           0.0

[260 rows x 18 columns]